config/routes.rb
Roulette::Application.routes.draw do
  resources :spins
  root 'spins#new'

end

app/models/location.rb
class Location < ActiveRecord::Base
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spins_controller.rb
class SpinsController < ApplicationController
  
  def new
    @spots = []
  end

  def create
    location = request.location 
    @client = GooglePlaces::Client.new('AIzaSyB_QWi7zPKtb69Nl11UJoFUsaxqZZztYWk')
    @spots = @client.spots(location.latitude, location.longitude, :types => 'restaurant')
    # methods are: location.latitude, location.longitude
    # @spots = @client.spots(51.5033630, -0.1276250, :types => 'restaurant')    
    
    # find restaurant by location
    # @restaurant = [ restaurant ]
    @spot = "hey"
    render 'new' 
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spins_helper.rb
module SpinsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roulette | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <script>
  
  </script>
</head>

<body>

<%= yield %>

</body>
</html>

app/views/spins/new.html.erb
<h1>Spins#new</h1>
<p>Find me in app/views/spins/new.html.erb</p>

<div style='width: 800px;'>
  <iframe
  width="450"
  height="250"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/search?key=AIzaSyB_QWi7zPKtb69Nl11UJoFUsaxqZZztYWk&q=restaurants">
  </iframe>
</div>
<div>
  <%= form_tag spins_path do %>
	  <%= submit_tag "Spin the wheel" %>
  <% end %>
</div>

<% if @spots %>
  <% @spots.each do |spot| %>
    <p><%= spot.name %></p>
  <% end %>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Restaurant Roulette</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>